# Generated by Django 4.1.1 on 2022-09-28 12:21

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('fonction', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DossierZip',
            fields=[
                ('id_zip', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dossier', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
            ],
            options={
                'db_table': 'dossierzip',
            },
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id_echantillon', models.AutoField(primary_key=True, serialize=False)),
                ('date_echantillon', models.DateField()),
                ('pays_origine', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'echantillon',
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id_fichier', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'fichier',
            },
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=100)),
                ('machine_user', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ordinateur',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id_run', models.AutoField(primary_key=True, serialize=False)),
                ('date_run', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'run',
            },
        ),
    ]
