# Generated by Django 4.1.1 on 2022-09-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing_module_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Ordinateur',
            },
        ),
    ]
